version: "3.9"
services:
  app:
    build: .
    ports:
      - "5001:5000"
    command: python manage.py --debug run -h 0.0.0.0
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code/
    depends_on:
      - db

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
